### ISSUE TITLE
variable encryption fails if no encrypted="false" given

### ISSUE THREAD

**Issue by tobiaszuercher** [tobiaszuercher/transformer#19]

**Comment by michaelschnyder** [comment]
Is there already an updated version of transformer on nuget containing this fix? Current Version on nuget is: 1.2.0.75

**Comment by tobiaszuercher** [comment]
sorry i forgot to hit the "push to nuget" button... #automation.

its in 1.2.0.76. after upgrading, i'd recommend restarting vs quickly (to reload the powershell module. it actually does it but the unloading of loaded powershell module is kind of shaky).

thank you very much for your valuable input michael!
